resources:
  - ../../base

namespace: staging

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/payment-service
    newTag: ${GITHUB_SHA}

replicas:
  - name: payment-service
    count: 1