apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "0"

  labels:
    prometheus: kube-prometheus

spec:
  selector:
    matchLabels:
      app: redis-exporter

  endpoints:
    - port: metrics
      interval: 30s