resources:
- ../../base
- external-secret.yaml

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/product-service
    newName: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/product-service
    newTag: c98b07e2fbe4776c7228e71e08e99ab05dcd4ba1



replicas:
- count: 1
  name: product-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
