resources:
  - ../../base
  - external-secret.yaml

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/product-service
    newTag: ea494678bf51784dfc04e4c2a37d7eebdadf13b1


replicas:
  - name: product-service
    count: 1