resources:
  - ../../base

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/product-service
    newTag: f40c788e9f4194b6fe33102e7ba174c37dcb59f4

replicas:
  - name: product-service
    count: 1