provider: aws

policy: sync

registry: txt

txtOwnerId: ${CLUSTER_NAME}

domainFilters:
  - ${BASE_DOMAIN}

serviceAccount:
  create: true
  name: external-dns

serviceMonitor:
  enabled: true
  additionalLabels:
    prometheus: kube-prometheus