apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service

spec:
  replicas: 2

  revisionHistoryLimit: 5 

  selector:
    matchLabels:
      app: order-service

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: order-service

    spec:
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: order-service

      containers:
        - name: order-service
          image: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/order-service
          imagePullPolicy: IfNotPresent

          securityContext:          
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL


            volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

          volumes:
          - name: tmp-volume
            emptyDir: {}

          resources:         
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          lifecycle:              
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10


          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe: 
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            
          startupProbe:
            httpGet:
              path: /health
              port: 8083
            failureThreshold: 30
            periodSeconds: 10

          ports:
            - containerPort: 8083

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: host

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: host

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: port
                  

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: database

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: password