apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: user-service-dev

spec:

  source:
    repoURL: https://github.com/Emmy-github-webdev/Kubernetes-argocd.git
    path: apps/order-service/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true