apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd

spec:
  source:
    helm:
      valueFiles:
        - $values/platform/monitoring/base/kube-prometheus-stack/values-common.yaml
        - $values/platform/monitoring/overlays/prod/values-prod.yaml