apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: default

  sources:
    # Helm chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 72.6.0

      helm:
        valueFiles:
          - $values/platform/monitoring/base/kube-prometheus-stack/values-common.yaml

    # Git repository containing the values files
    - repoURL: https://github.com/Emmy-github-webdev/Kubernetes-argocd.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
