grafana:

  adminPassword: admin

  persistence:

    enabled: true

    size: 20Gi

  service:

    type: ClusterIP

prometheus:

  prometheusSpec:

    retention: 30d

    retentionSize: 30GB

    storageSpec:

      volumeClaimTemplate:

        spec:

          storageClassName: gp3

          accessModes:

          - ReadWriteOnce

          resources:

            requests:

              storage: 50Gi

alertmanager:

  enabled: true

kubeStateMetrics:

  enabled: true

nodeExporter:

  enabled: true