grafana:
  enabled: true

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP

  persistence:
    enabled: true
    storageClassName: gp3
    size: 20Gi

  defaultDashboardsEnabled: false

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

      folder: /var/lib/grafana/dashboards
      folderAnnotation: grafana_folder

      provider:
        foldersFromFilesStructure: true

      label: grafana_dashboard
      labelValue: "1"
      watchMethod: WATCH

    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
