apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-notification-secret
  namespace: dev

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: alertmanager-notification-secret

  data:
    - secretKey: slack-webhook
      remoteRef:
        key: alertmanager/notifications
        property: slack-webhook