apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: alertmanager-notification-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager

  target:
    name: alertmanager-notification-secret
    creationPolicy: Owner

  data:
    - secretKey: slack-webhook
      remoteRef:
        key: alertmanager/notifications
        property: slack-webhook