apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- external-secret.yaml

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/order-service
    newName: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/order-service
    newTag: e2bab85bf8a0e4f650228147471ae175a246cc09

replicas:
- count: 1
  name: order-service

