resources:
  - ../../base

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/order-service
    newTag: 089d71f10d4108293b01d4c883d08c8430286f93

patchesStrategicMerge:
  - external-secret-patch.yaml

replicas:
  - name: order-service
    count: 1