resources:
- ../../base
- external-secret.yaml

namespace: dev

images:
  - name: order-service
    newName: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/order-service
    newTag: 6e5d6e990faca1534f02d7e9989eaaac66277e39

replicas:
- count: 1
  name: order-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
