resources:
- ../../base
- external-secret.yaml

namespace: staging

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/product-service
    newName: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/product-service
    newTag: 28693b4fcc780e82605d4368b13dc437037b4567



replicas:
- count: 1
  name: product-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
