apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: payment-db-config
  namespace: platform

spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: payment-db-config

  dataFrom:
    - extract:
        key: /staging/payment/db