apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: staging

spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: redis-secret
    creationPolicy: Owner

  data:
    - secretKey: host
      remoteRef:
        key: /staging/redis/cache
        property: host

    - secretKey: port
      remoteRef:
        key: /staging/redis/cache
        property: port