apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: node-recording-rules
  namespace: dev

  labels:
    prometheus: kube-prometheus

spec:
  groups:

    - name: node.recording.rules

      interval: 30s

      rules:

        - record: node:cpu_usage:ratio

          expr: |
            1 -
            avg by(instance)
            (
              rate(
                node_cpu_seconds_total{
                  mode="idle"
                }[5m]
              )
            )


        - record: node:memory_usage:ratio

          expr: |
            1 -
            (
              node_memory_MemAvailable_bytes
              /
              node_memory_MemTotal_bytes
            )


        - record: node:disk_usage:ratio

          expr: |
            1 -
            (
              node_filesystem_avail_bytes
              /
              node_filesystem_size_bytes
            )