apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: require-networkpolicy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    
spec:
  validationFailureAction: Audit

  background: true

  rules:

    - name: require-networkpolicy-label

      match:
        any:
          - resources:
              kinds:
                - Deployment

      validate:
        message: "Deployment must define networkpolicy.enabled=true label."

        pattern:
          metadata:
            labels:
              networkpolicy.enabled: "true"