apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-db-secret
  namespace: product
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: product-db-secret