apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  - cluster-secret-store.yaml
  - ingress.yaml
  - namespace-infra.yaml
  - postgres-master-secret.yaml
  - external-secrets-sa.yaml
  - redis-secret.yaml
  - job.yaml