apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: postgres-master
  namespace: platform

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: postgres-master

  dataFrom:
    - extract:
        key: /dev/postgres/master