apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: product-db-config
  namespace: platform

spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: product-db-secret

  dataFrom:
    - extract:
        key: /dev/product/db