apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: user-db-config
  namespace: platform

spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: user-db-config

  dataFrom:
    - extract:
        key: /prod/user/db