apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.4

    helm:
      values: |
        clusterName: REPLACE_ME
        region: REPLACE_ME
        vpcId: REPLACE_ME

        serviceAccount:
          create: true
          name: aws-load-balancer-controller

        replicaCount: 2

        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              prometheus: kube-prometheus

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true