apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd

spec:
  destination:
    namespace: dev

  source:
    helm:
      values: |
        clusterName: eks-dev-cluster
        region: us-east-1
        vpcId: vpc-068d485a36c94f6c1

        serviceAccount:
          create: true
          name: aws-load-balancer-controller

        replicaCount: 2

        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              prometheus: kube-prometheus