apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller

spec:
  source:
    helm:
      values: |
        clusterName: eks-dev-cluster
        region: us-east-1
        vpcId: vpc-0ed36055c1f322ad8

        serviceAccount:
          create: true
          name: aws-load-balancer-controller

        replicaCount: 2

        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              prometheus: kube-prometheus