apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ingress-namespace.yaml
  - external-dns-patch.yaml
  - aws-load-balancer-controller-patch.yaml
  - letsencrypt-patch.yaml