apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ingress/overlays/prod
  - ../../logging/overlays/prod
  - ../../monitoring/overlays/prod
  - ../../networking/overlays/prod
  - ../../security/overlays/prod
  - ../../tracing/overlays/prod
  - ../../storage/overlays/prod