apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service

spec:
  replicas: 2

  revisionHistoryLimit: 5 

  selector:
    matchLabels:
      app: user-service

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: user-service

    spec:
      terminationGracePeriodSeconds: 30

      volumes:
        - name: tmp-volume
          emptyDir: {}
          
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: user-service

      containers:
        - name: user-service
          image: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/user-service
          imagePullPolicy: IfNotPresent

          securityContext:          
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

          resources:         
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          lifecycle:              
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10


          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe: 
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 30
            periodSeconds: 10

          ports:
            - containerPort: 8081

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: userer-db-secret
                  key: host

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: host

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: port

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: database

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: password

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: port
                  