apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-db-secret
  namespace: user
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: user-db-secret