apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: opentelemetry-collector
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.113.0

    helm:
      valueFiles:
        - values-common.yaml

  destination:
    server: https://kubernetes.default.svc


  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true