resources:
  - ../../base

namespace: staging

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/user-service
    newTag: ${GITHUB_SHA}

patchesStrategicMerge:
  - external-secret-patch.yaml

replicas:
  - name: user-service
    count: 1