apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd

spec:
  destination:
    namespace: staging

  source:
    helm:
      values: |
        clusterName: eks-staging-cluster
        region: us-east-1
        vpcId: vpc-0ee0ba3a1edd3517c

        serviceAccount:
          create: true
          name: aws-load-balancer-controller

        replicaCount: 2

        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              prometheus: kube-prometheus