apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - letsencrypt.yaml

patches:
  - path: external-dns-patch.yaml
  - path: aws-load-balancer-controller-patch.yaml