apiVersion: v1
kind: ConfigMap

metadata:
  name: opentelemetry-java-agent-config
  namespace: tracing


data:

  JAVA_TOOL_OPTIONS: >-
    -javaagent:/otel/opentelemetry-javaagent.jar


  OTEL_SERVICE_NAME: order-service


  OTEL_EXPORTER_OTLP_ENDPOINT: >-
    http://opentelemetry-collector.tracing.svc.cluster.local:4317


  OTEL_EXPORTER_OTLP_PROTOCOL: grpc


  OTEL_TRACES_EXPORTER: otlp


  OTEL_METRICS_EXPORTER: none


  OTEL_LOGS_EXPORTER: none


  OTEL_RESOURCE_ATTRIBUTES: >-
    service.namespace=dev