apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: prod-infrastructure
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: infrastructure
            path: infrastructure/overlay/prod
            namespace: prod

template:
  metadata:
    name: '{{name}}-prod'

  spec:
    project: default

    source:
      repoURL: https://github.com/Emmy-github-webdev/Kubernetes-argocd.git
      targetRevision: main
      path: apps/{{name}}/overlays/prod

    destination:
      server: https://kubernetes.default.svc
      namespace: prod

    revisionHistoryLimit: 5

    syncPolicy:
      automated:
        prune: true
        selfHeal: true

      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m

      syncOptions:
        - CreateNamespace=true   
                                                                                                                                                                                   