apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: prod-monitoring
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: monitoring
            path: platform/overlays/prod
            namespace: prod

  template:
    metadata:
      name: "{{name}}-prod"

    spec:
      project: default

      source:
        repoURL: https://github.com/Emmy-github-webdev/Kubernetes-argocd.git
        targetRevision: main
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true                                                                                                                                                    