apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: staging-monitoring
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: monitoring
            path: platform/overlays/staging
            namespace: staging

  template:
    metadata:
      name: "{{name}}-staging"

    spec:
      project: default

      source:
        repoURL: https://github.com/Emmy-github-webdev/Kubernetes-argocd.git
        targetRevision: main
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true                                                                                                                                                    