apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager/
  - networkpolicies/
  - grafana/
  - postgres-exporter/
  - redis-exporter/
  - blackbox-exporter/
  - prometheusrules/
  - recording-rules/
  - servicemonitors/

  - external-secret.yaml
  - application.yaml
  - kustomization.yaml
  - values-common.yaml
  