resources:
- ../../base
- external-secret.yaml

namespace: dev

images:
- name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/payment-service
  newTag: 5e8c536ef5b688df7bb54b42d45d5a2285ec7de2
- name: payment-service
  newName: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/payment-service
  newTag: b23b6ebb1e48c7095f99e4760155fe5d91952f6f


replicas:
- count: 1
  name: payment-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
