apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ingress/overlays/staging
  - ../../logging/overlays/staging  
  - ../../monitoring/overlays/staging
  - ../../networking/overlays/staging
  - ../../security/overlays/staging
  - ../../tracing/overlays/staging
  - ../../storage/overlays/staging