apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-notification-secret
spec:
  data:
    - secretKey: slack-webhook
      remoteRef:
        key: dev-alertmanager/notifications
        property: slack-webhook