apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: dev-infrastructure
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: ingress
            path: infrastructure/overlay/dev
            namespace: dev

  template:
    metadata:
      name: '{{name}}-dev'

    spec:
      project: default

      source:
        repoURL: https://github.com/Emmy-github-webdev/Kubernetes-argocd.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true                    