resources:
  - ../../base

namespace: staging

images:
  # - name: ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/order-service
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/test
    newTag: latest

replicas:
  - name: order-service
    count: 1