apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: default

  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 11.1.1

    helm:
      valueFiles:
        - values-common.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: true
      selfHeal: true