credentials:
  useSecret: false

initContainers:
  - name: velero-plugin-for-aws

    image: velero/velero-plugin-for-aws:v1.11.0

    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation: []

  volumeSnapshotLocation: []

snapshotsEnabled: true

deployNodeAgent: true