resources:
  - ../../base

namespace: prod

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/order-service
    newTag: ${GITHUB_SHA}

patchesStrategicMerge:
  - external-secret-patch.yaml

replicas:
  - name: order-service
    count: 1
