resources:
  - ../../base
  - external-secret.yaml

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/user-service
    newTag: c84b5d46cceb7ccfcb9bd6dec34c8e3814b58096

  
replicas:
  - name: user-service
    count: 1