resources:
- ../../base
- external-secret.yaml

namespace: dev

images:
  - name: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/user-service
    newName: 579871530627.dkr.ecr.us-east-1.amazonaws.com/ja-mics-ap/user-service
    newTag: 09456fa8825fd5fb40f4736109f5e1115bbb816e


  
replicas:
- count: 1
  name: user-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
